services:
  - type: web
    name: farewell-social-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npx tsx src/server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CLIENT_ORIGIN
        value: https://frontend-ten-alpha-54.vercel.app
